### ISSUE TITLE
The UI can show other assets like fees  instead of weth- EVM

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#772]
If you send other asset to an new account, put that asset like fees on the UI, but at the moment of sign.... 
![IMG_20231127_195439_415](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/464c32ee-9dd5-43a8-8d81-178273353efa)

**Comment by jak-pan** [comment]
This is a bug. Talisman evm should be behaving like native metamask and in this case show weth

**Comment by mrq1911** [comment]
@jvonasek could this be exception because user is trying to set HDX as payment currency, therefore there is exception that UI expects this being payed in this new currency?

it is impossible for evm users to change their payment currency - they can set it to different asset, but they will be always charged WETH anyway

**Comment by jvonasek** [comment]
@mrq1911 there was a specific flow where user is prompted to change payment asset in the transaction review modal, if there is not enough balance to pay the fee.

![evmpaymentasset](https://github.com/galacticcouncil/HydraDX-ui/assets/3890412/87f39c5c-45af-499f-95d1-5d4de3b0f85d)

I made a fix so that EVM accounts don't get this prompt and only warning message will be displayed and "Sign" button disabled.

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/3890412/74759586-7b72-423e-b15c-6154ec9f6a28)

**Comment by DuriSK** [comment]
Solved
